[package]
name = "paia-shuffler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.5.0"
rand = "0.8.5"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
